site_name: Py-DES

theme:
  logo: assets/pydes-logo.png
  name: "material"
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - content.code.copy  
    # - navigation.tabs
  icon:
    repo: fontawesome/brands/git-alt 

repo_url: https://github.com/vitostamatti/pydes
repo_name: vitostamatti/pydes


plugins:
  - search:
  - gen-files:
      scripts:
      - docs/scripts/gen_ref_pages.py  
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_docstring_functions: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_source: false
            merge_init_into_class: true
            members_order: source
            # summary: true
            # show_category_heading: true
            # allow_inspection: true  
  - section-index:

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html


nav:
  - index.md
  - Overview: overview.md
  - Quick Start: quick-start.md
  - Examples: examples/
  - Reference: reference/
    # - ./examples/index.md
    # - ./examples/01-process-example.md
    # - py-des-events: 
    # # reference/py-des/events/__init__.md
    #   - core: reference/py-des/events/core.md
    # - py-des-process: 
    #   - core: reference/py-des/process/core.md
    #   - components: reference/py-des/process/components.md

  # - Reference: reference.md
